### PR TITLE
Fix typos in SeaFET functions

### PR DESCRIPTION
**Pull request by umihoshijima**
The first lines in the seaFET functions refer to variables which do not exist in the functions. I corrected these so that these lines would work as intended. 

I first came across the issue when I tried to calibrate SeaFET data using a single E0_25. The error I got was a strange one ("Object P not found"), which led me to look into these functions.

### CODE REVIEW

**Comment by jpgattuso** [comment]
Thank you very much for noticing this silly mistake and for proposing a fix.

**Comment by jpgattuso** [comment]
Note that your fix was incomplete. Watch out for 3.2.4 on CRAN. Thanks anyway for spotting the mistake!

**Comment by umihoshijima** [comment]
Thank you for providing and maintaining this resource for the community! I am finishing up my Ph.D. with Gretchen Hofmann here in California, and use `seacarb` extensively for my work.

**Comment by jpgattuso** [comment]
Thanks! It is always great to know that the package is useful.

Regards, jp



-- 
Jean-Pierre Gattuso | http://www.obs-vlfr.fr/~gattuso | @jpGattuso

On 15 January 2018 at 22:45:07, Umihiko Hoshijima (notifications@github.com) wrote:

Thank you for providing and maintaining this resource for the community! I am finishing up my Ph.D. with Gretchen Hofmann here in California, and use seacarb extensively for my work.

**Pull request merged**
