### PR TITLE
added Bt to error propagation, changed step size to 1e-6

### PR DESCRIPTION
**Pull request by jamesorr**
* Added total boron as an eight "constant" that is now accounted for in the error propagation (changes to errors.r and derivnum.R).

* Changed step size in derivnum.R to be consistent with other packages (CO2SYS-MATLAB, ...)

* buffesm routine improved (separating contributions from Pt and Sit to Segle)

### CODE REVIEW

**Comment by jamesorr** [comment]
The third item mentioned above (regarding buffesm) was already made previously.  So there are actually no changes here regarding buffesm.  Only two routines are changed (errors.R and derivnum.R).

**Comment by jpgattuso** [comment]
Jim,

This comment is on the wrong branch (teos-eos). I could not find how to 
merge it with the master branch. Perhaps you could make the commit on 
the base branch?

Sorry about my clumsiness with Github!

Jean-Pierre

On 23 Jan 2017, at 9:41, James Orr wrote:

> The third item mentioned above (regarding buffesm) was already made 
> previously. So there are actually no changes here regarding buffesm. 
> Only two routines are changed (errors.R and derivnum.R).
>
>


---------------------------------------------
Jean-Pierre Gattuso | http://www.obs-vlfr.fr/~gattuso | @jpGattuso

**Comment by jpgattuso** [comment]
Il faut que l’on se parle au téléphone.


On 23 Jan 2017, at 9:36, James Orr wrote:

> * Added total boron as an eight "constant" that is now accounted for 
> in the error propagation (changes to errors.r and derivnum.R).
>
> * Changed step size in derivnum.R to be consistent with other packages 
> (CO2SYS-MATLAB, ...)
>
> * buffesm routine improved (separating contributions from Pt and Sit 
> to Segle)
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/jpgattuso/seacarb-git/pull/35
>
> -- Commit Summary --
>
>   * added Bt to error propagation, changed step size to 1e-6
>
> -- File Changes --
>
>     M R/derivnum.R (52)
>     M R/errors.R (39)
>
> -- Patch Links --
>
> https://github.com/jpgattuso/seacarb-git/pull/35.patch
> https://github.com/jpgattuso/seacarb-git/pull/35.diff
>
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/jpgattuso/seacarb-git/pull/35




---------------------------------------------
Jean-Pierre Gattuso | http://www.obs-vlfr.fr/~gattuso | @jpGattuso

**Comment by jamesorr** [comment]
Closing this pull request as it has been replaced by the following one, the same changes but with the pull request made relative to the master branch.

**Pull request closed without merging**
